sudo: required
dist: trusty
language: java
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - rpm
install:
  - git clone --branch 2.4 --depth=1 --no-single-branch https://github.com/Graylog2/graylog2-server ../graylog2-server
  - (cd ../graylog2-server && mvn -DskipTests=true compile -B -V)
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dskip.web.build=true -B -V
script:
  - mvn package -B
before_deploy:
#  - mvn jdeb:jdeb && export RELEASE_DEB_FILE=$(ls target/*.deb)
#  - mvn rpm:rpm && export RELEASE_RPM_FILE=$(find target/ -name '*.rpm' | tail -1)
  - rm -f target/original-*.jar
  - export RELEASE_JAR_FILE=$(ls target/*.jar)
  - echo "Deploying release to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: TBD
  file:
    - "${RELEASE_JAR_FILE}"
#    - "${RELEASE_DEB_FILE}"
#    - "${RELEASE_RPM_FILE}"
  skip_cleanup: true
  on:
    tags: true
    jdk: oraclejdk8